apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: demo
spec:
  clusterIP: None   # headless
  selector:
    app: svc-b
  ports:
    - name: http
      port: 8082
      targetPort: 8082
