apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: svc-b
  namespace: demo
spec:
  serviceName: svc-b
  replicas: 2
  selector:
    matchLabels:
      app: svc-b
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: svc-b
          image: prash609/microservice-b:1.0.0
          ports:
            - containerPort: 8082
          # Probes (adjust if you don't use Actuator)
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
