apiVersion: v1
kind: Service
metadata:
  name: microservice-a
spec:
  selector:
    app: microservice-a
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: choose a port between 30000-32767
  type: NodePort
